SELECT
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT S.USER_ID) / 
        (
            SELECT COUNT(*)
            FROM USER_INFO
            WHERE JOINED >= '2021-01-01' AND JOINED < '2022-01-01'
        ),
        1
    ) AS PUCHASED_RATIO
FROM USER_INFO I
JOIN ONLINE_SALE S ON I.USER_ID = S.USER_ID
WHERE I.JOINED >= '2021-01-01' AND I.JOINED < '2022-01-01'
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR, MONTH;